name: HFST CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
           sudo apt-get -qy update
           sudo apt-get -qfy install --no-install-recommends curl ca-certificates
           curl -sS https://apertium.projectjj.com/apt/install-nightly.sh | sudo bash
           sudo apt-get -qfy install --no-install-recommends build-essential automake autotools-dev pkg-config python3-dev python3-setuptools swig bison flex libicu-dev libreadline-dev libtool zlib1g-dev libfst-dev libfoma-dev
    - name: autoreconf
      run: autoreconf -fvi
    - name: configure
      run: ./configure --disable-static --enable-all-tools --with-readline --with-unicode-handler=icu --with-openfst-upstream --with-foma-upstream --enable-python-bindings
    - name: build
      run: make -j4 V=1 VERBOSE=1
    - name: tests
      run: make check V=1 VERBOSE=1
    - name: make install
      run: sudo make install
